### ISSUE TITLE
Not working with array

### ISSUE THREAD

**Issue by absolutejam** [spencerdcarlson/ex_jq#3]
Hey,

Thanks for this - It's crazy how much I rely on `jq` and it's (going to be) a key part of a project I'm working on.

I'm just testing the library out and noticed that it is throwing an exception on the following query:
```ruby
JQ.query(%{"changes" => %{"labels" => [ %{"title"=>"foo"}, %{"title"=>"bar"} ]}}, ".changes.labels[].title")
```
I only seem to hit errors when using array notation, and I noticed in the terminal, it spits this out as the following (not raw):
```
"API"
"bug"
```
I guess `Poison` is trying to decode this but it's obviously not valid JSON.

I've tried removing the `File.rm!` out so I can inspect the file but it just contains the data structure as json:
```json
{"changes":{"labels":[{"title":"foo"},{"title":"bar"}]}}
```

Wrapping the above query in an array (`[.changes.labels[].title]`) works, but I'm curious to see if there's a way to debug this and maybe add some niceness - either a `not valid json` error or some logic to automatically create an array for multiple objects. If you have any ideas, I'll be willing to add an MR.

Regards,
James.

**Comment by absolutejam** [comment]
Added some debugging messages and recompiling, I can confirm it's what I thought. I'll look at possibly throwing an 'invalid JSON' error at the `Poison.decode!` for the time-being.

**Comment by dfang** [comment]
i got same error

```
iex(68)> [%{a: 1, b: 2, c: 3}, %{a: 1, b: 2, c: 3}] |> JQ.query!(".[]")
** (Poison.ParseError) Unexpected token at position 33: {
    (poison 4.0.1) lib/poison/parser.ex:353: Poison.Parser.parse!/2
    (jq 1.0.2) lib/jq.ex:95: JQ.query!/3
```
