### ISSUE TITLE
new owner?

### ISSUE THREAD

**Issue by epinault** [spencerdcarlson/ex_jq#5]
Hello! would you be willing to give this up so we can take over the package name in Hex.pm and make it more robust? there is an erlang NIF that is better but the name collide and would be nice to be able to use the more performant NIF version

**Comment by epinault** [comment]
@spencerdcarlson let me know what you think

**Comment by spencerdcarlson** [comment]
Yeah, this package is gross that it shell's out. I just requested to transfer it to you @epinault.

**Comment by spencerdcarlson** [comment]
@epinault what is the hex username I should send the hex package to?

**Comment by epinault** [comment]
same than here :)

**Comment by spencerdcarlson** [comment]
Added [jq](https://hex.pm/packages/jq)

**Comment by epinault** [comment]
thank you! ❤️
